test_concatString (__main__.SumTest) ... ERROR
test_concatString2 (__main__.SumTest) ... ERROR

======================================================================
ERROR: test_concatString (__main__.SumTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/soethandara/Desktop/PLAS/Ishihara/Python-NPLAS/routes/../addon/submits/concatStringTest.py", line 17, in test_concatString
    result_test = self.concatenation.concatString1(self.a, self.b)
AttributeError: Concatenation instance has no attribute 'concatString1'

======================================================================
ERROR: test_concatString2 (__main__.SumTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/soethandara/Desktop/PLAS/Ishihara/Python-NPLAS/routes/../addon/submits/concatStringTest.py", line 23, in test_concatString2
    result_test = self.concatenation.concatString2(self.a, self.b, self.c)
AttributeError: Concatenation instance has no attribute 'concatString2'

----------------------------------------------------------------------
Ran 2 tests in 0.000s

FAILED (errors=2)
